# Generated by Django 4.2.7 on 2023-12-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성날짜"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정날짜"),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성날짜"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정날짜"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("text", models.TextField(verbose_name="본문")),
                (
                    "relation_posts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="relation_post",
                        to="apps.post",
                        verbose_name="연관게시글",
                    ),
                ),
                ("tag_set", models.ManyToManyField(blank=True, to="apps.tag")),
            ],
            options={"abstract": False,},
        ),
    ]
