# Generated by Django 4.2.7 on 2023-12-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="relation_posts",
            field=models.ManyToManyField(
                blank=True, to="apps.post", verbose_name="연관게시글"
            ),
        ),
    ]
